### ISSUE TITLE
BUG Can't find in array using Query

### ISSUE THREAD

**Issue by coffeemachine** [mongojack/mongojack#12]
"Item" is a very simple class with an @Id String id and a List&lt;String&gt; tags, and proper getters/setters.

``` java
Mongo mongo = new Mongo("localhost");
DB db = mongo.getDB("mongojack-test");
DBCollection coll = db.createCollection("items", null);

JacksonDBCollection<Item, String> items = JacksonDBCollection.wrap(coll, Item.class, String.class);

// Doesn't work
items.find().is("tags", "one").toArray();

// Doesn't work
Query q = DBQuery.is("tags", "one");
items.find(q).toArray();        
```

Stacktrace:

Exception in thread "main" java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Collection
    at com.fasterxml.jackson.databind.ser.impl.StringCollectionSerializer.serialize(StringCollectionSerializer.java:24)
    at org.mongojack.internal.util.SerializationUtils.serializeQueryField(SerializationUtils.java:219)
    at org.mongojack.internal.util.SerializationUtils.serializeQueryCondition(SerializationUtils.java:145)
    at org.mongojack.internal.util.SerializationUtils.serializeQuery(SerializationUtils.java:124)
    at org.mongojack.internal.util.SerializationUtils.serializeQuery(SerializationUtils.java:116)
    at org.mongojack.JacksonDBCollection.serializeQuery(JacksonDBCollection.java:1707)
    at org.mongojack.JacksonDBCollection.find(JacksonDBCollection.java:829)
    at mongojack.Main.main(Main.java:29)

**Comment by spuggiehawk** [comment]
It has been over 2 years since this bug received a comment.  Has this been addressed yet?  Is that because it hasn't been assigned to anyone?

I seem to be suffering the same issue with the DBQuery.elemMatch(String field, DBQuery.Query query).
This looks like it should be the correct method to use.  But if it is, then what should `query` look like?  Specifically, using the `{tags: ["fun", "cats"]}` example above...

`collection.find(DBQuery.elemMatch("tags", ???)`

I have got the behaviour that I need by using the DBQuery.all method, but it looks like it would be better if elemMatch worked.
