### ISSUE TITLE
DBQuery.all fails with list of non primitive elements

### ISSUE THREAD

**Issue by ractive** [mongojack/mongojack#134]
Doing a `DBQuery.all("myobject.mylist.id", 1, 2, 3)` fails if mylist is a `List` containing objects.

The stack trace is:
```
java.lang.ClassCastException: java.util.Arrays$ArrayList cannot be cast to java.lang.Integer
	at com.fasterxml.jackson.databind.ser.std.NumberSerializers$IntegerSerializer.serialize(NumberSerializers.java:144)
	at org.mongojack.internal.util.SerializationUtils.serializeQueryField(SerializationUtils.java:263)
	at org.mongojack.internal.util.SerializationUtils.serializeQueryCondition(SerializationUtils.java:181)
	at org.mongojack.internal.util.SerializationUtils.serializeQueryCondition(SerializationUtils.java:165)
	at org.mongojack.JacksonDBCollection.serializeQueryCondition(JacksonDBCollection.java:2292)
	at org.mongojack.DBCursor.put(DBCursor.java:561)
	at org.mongojack.DBCursor.put(DBCursor.java:1)
	at org.mongojack.DBQuery$AbstractBuilder.all(DBQuery.java:509)
	at org.mongojack.DBQuery$AbstractBuilder.all(DBQuery.java:523)
	at org.mongojack.TestDBQuery.testAllEmbeddedPositive(TestDBQuery.java:324)
	...
```

**Comment by ractive** [comment]
Please see https://github.com/mongojack/mongojack/pull/135
