### ISSUE TITLE
Problem with UUID as Id

### ISSUE THREAD

**Issue by ItsBlockFighter** [mongojack/mongojack#216]
I got this error back when I want to use UUID as Id.
```
java.lang.IllegalArgumentException: Unsupported ID type: class java.util.UUID
        at org.mongojack.internal.stream.JacksonCodec.constructIdValue(JacksonCodec.java:267) ~[mongojack-4.2.0.jar:?]
        at org.mongojack.JacksonMongoCollection.createIdQuery(JacksonMongoCollection.java:231) ~[mongojack-4.2.0.jar:?]
        at org.mongojack.JacksonMongoCollection.findOneById(JacksonMongoCollection.java:215) ~[mongojack-4.2.0.jar:?]
```
        
```java
    import org.mongojack.Id;

    @Id
    private UUID uuid;
```

**Comment by rlodge** [comment]
Yes, there's some code in org.mongojack.internal.stream.JacksonCodec that limits the ID types.  I don't see a reason why it couldn't support UUIDs as valid types.  You're welcome to supply a pull request with tests for such a feature.

**Comment by rlodge** [comment]
Should be working in 4.5.1 and 4.7.0.
