### ISSUE TITLE
 Error mapping BSON to POJOs with $pull DBQuery vs BasicDBObject

### ISSUE THREAD

**Issue by jayv** [mongojack/mongojack#23]
This fails for some reason:

```
        getJacksonCollection().updateById(presentationId, publishContent(user).pull("publishContent.library", DBQuery.is("id", libraryItemId)));

        org.mongojack.MongoJsonMappingException: Error mapping BSON to POJOs
            at org.mongojack.internal.util.SerializationUtils.serializeField(SerializationUtils.java:288) ~[mongojack-2.0.0-RC5.jar:na]
            at org.mongojack.internal.util.SerializationUtils.serializeDBUpdate(SerializationUtils.java:320) ~[mongojack-2.0.0-RC5.jar:na]
            at org.mongojack.DBUpdate$Builder.serialiseAndGet(DBUpdate.java:527) ~[mongojack-2.0.0-RC5.jar:na]
            at org.mongojack.JacksonDBCollection.updateById(JacksonDBCollection.java:476) ~[mongojack-2.0.0-RC5.jar:na]
```

while this works:

```
    getJacksonCollection().updateById(presentationId, publishContent(user).pull("publishContent.library", new BasicDBObject("id", libraryItemId)));
```

is this a bug or expected behavior?

**Comment by broundee** [comment]
I have some similar code broken as well, the root cause is https://github.com/devbliss/mongojack/issues/62
