### ISSUE TITLE
Serializing objects with Dates causes a StackOverflowError

### ISSUE THREAD

**Issue by dgileadi** [mongojack/mongojack#26]
I've applied MongoJackModule.configure to an ObjectMapper and am calling mapper.writeValueAsString on a HashMap that has a Date as one of its values. When I do this I get a StackOverflowError. Here's the top part of the trace:

java.lang.StackOverflowError
    at com.fasterxml.jackson.databind.ser.SerializerCache.getReadOnlyLookupMap(SerializerCache.java:48)
    at com.fasterxml.jackson.databind.SerializerProvider.<init>(SerializerProvider.java:198)
    at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.<init>(DefaultSerializerProvider.java:63)
    at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider$Impl.<init>(DefaultSerializerProvider.java:437)
    at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider$Impl.createInstance(DefaultSerializerProvider.java:443)
    at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider$Impl.createInstance(DefaultSerializerProvider.java:429)
    at com.fasterxml.jackson.databind.ObjectMapper._serializerProvider(ObjectMapper.java:2687)
    at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:1819)
    at com.fasterxml.jackson.core.base.GeneratorBase.writeObject(GeneratorBase.java:259)
    at org.mongojack.internal.DateSerializer.serialize(DateSerializer.java:34)
    at org.mongojack.internal.DateSerializer.serialize(DateSerializer.java:31)
    at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:118)
    at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:1819)
    at com.fasterxml.jackson.core.base.GeneratorBase.writeObject(GeneratorBase.java:259)
    at org.mongojack.internal.DateSerializer.serialize(DateSerializer.java:34)
    at org.mongojack.internal.DateSerializer.serialize(DateSerializer.java:31)

I've verified that if I don't call MongJackModule.configure on the ObjectMapper that the error doesn't happen.

I'm using MongoJack 2.0.0-RC5 with Jackson 2.2.3.

**Comment by jochenberger** [comment]
and 2.2.0

**Comment by thomasbratt** [comment]
and 2.6.0

**Comment by lukepalmer** [comment]
Would it be possible to submit a PR with a known failing test case with the @Ignore annotation? Needs to be against current versions (including current Jackson).

I have looked at something similar in the past and would be up for having a look.
