### ISSUE TITLE
JacksonDBCollection#removeById does not call serializeQuery

### ISSUE THREAD

**Issue by narbsy** [mongojack/mongojack#64]
Ran into an interesting problem with `JacksonDBCollection` when switching from a `String` id to a custom id object.

Calling `JacksonDBCollection#removeById` with this custom id gave a failure:

```
java.lang.IllegalArgumentException: can't serialize class <custom id class>
	at org.bson.BasicBSONEncoder._putObjectField(BasicBSONEncoder.java:270)
	at org.bson.BasicBSONEncoder.putObject(BasicBSONEncoder.java:155)
	at org.bson.BasicBSONEncoder.putObject(BasicBSONEncoder.java:120)
	at com.mongodb.DefaultDBEncoder.writeObject(DefaultDBEncoder.java:27)
	at com.mongodb.OutMessage.putObject(OutMessage.java:289)
	at com.mongodb.OutMessage.writeRemove(OutMessage.java:189)
	at com.mongodb.OutMessage.remove(OutMessage.java:69)
	at com.mongodb.DBApiLayer$MyCollection.remove(DBApiLayer.java:287)
	at com.mongodb.DBCollection.remove(DBCollection.java:250)
	at com.mongodb.DBCollection.remove(DBCollection.java:272)
	at org.mongojack.JacksonDBCollection.removeById(JacksonDBCollection.java:570)
```

Calling `JacksonDBCollection#findOneById` with the same custom id works as expected. Tracing the method calls shows that `findOneById` (eventually) ensures that it calls `serializeFields` on the query before passing it to mongo:

```
    public final org.mongojack.DBCursor<T> find(DBObject query, DBObject keys) {
        return new org.mongojack.DBCursor<T>(this, dbCollection.find(serializeFields(query), keys));
    }
```

I believe `removeById` should do something similar -- please let me know if this is incorrect. One way is to delegate in `removeById` to `remove`:

```
    public WriteResult<T, K> removeById(K id) throws MongoException {
        return remove(createIdQuery(id)));
    }
``` 

Thanks!

**Comment by kdkeck** [comment]
Exactly right, and fixed in latest release.

**Comment by narbsy** [comment]
Thanks @kdkeck!
